### PR TITLE
Move `eslint-config-zapier` to `eslint-plugin-zapier`

### PR DESCRIPTION
**Pull request by vitorbal**
Move `eslint-config-zapier` to `eslint-plugin-zapier` to allow us to also share custom rules.
This commit also adds the first custom rule, `disallow-lodash-get-dot-notation`.

Technically we should create a new repository to do this, but since no one actually uses this yet, this should be safe. I'll mark the `eslint-config-zapier` package in npm as deprecated and publish a new one called `eslint-plugin-zapier`

### CODE REVIEW

**Comment by ibolmo** [comment]
haha but I am :D https://github.com/zapier/zapier-platform-app-hootsuite/blob/master/package.json#L34

No worries, though, just tell me what I should do

**Comment by vitorbal** [comment]
@ibolmo wow cool! I didn't know haha :D no sweat, I see that you pin the version so you should be all good!
If/Once you migrate all you have to do is uninstall `eslint-config-zapier` and install `eslint-plugin-zapier`, and change from:

```json
{
  "extends": ["zapier"],
}
```

to:
```json
{
  "plugins": ["zapier"],
  "extends": ["plugin:zapier/base"],
}
```

**Comment by ibolmo** [comment]
cool I'll do this once you publish this, right?

**Comment by vitorbal** [comment]
@ibolmo I opened a PR for this change here: https://github.com/zapier/zapier-platform-app-hootsuite/pull/1

**Comment by vitorbal** [comment]
Merging this in to avoid confusion since I already published `eslint-plugin-zapier` to npm. I'll react to any change requests accordingly if anything comes up!

**Pull request merged**
